### ISSUE TITLE
Needs documentation

### ISSUE THREAD

**Issue by linuxsoftware** [linuxsoftware/ls.joyous#1]
Yes this project lacks documentation.  Please let me know what I should cover.  What questions would you like answered?

**Comment by bocian67** [comment]
It would be great to have a sample project with the settings to see with an example how to implement it right.

**Comment by linuxsoftware** [comment]
Started some rough notes on the Wiki
https://github.com/linuxsoftware/ls.joyous/wiki/Notes

**Comment by linuxsoftware** [comment]
Added documentation.  See https://joyous.readthedocs.io/en/latest/
