### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Jean-Zombie** [linuxsoftware/ls.joyous#11]
I'd like to help with the localization of Joyous. I would go like this:

1. Update my fork
2. run `django-admin makemessages --locale=de` in the module root
3. ask for a pull request

ok?

**Comment by linuxsoftware** [comment]
That would be great!  Thanks!!!

I have been running ``django-admin makemessages`` in the joyous module, i.e. going ``cd ls/joyous`` first.  (To avoid various temporary python files that end up in subdirectories off the project root.) It'd be good if you could do the same, thanks. 

I have created a Transifex project for Joyous.  Is it useful?  I am not sure. https://www.transifex.com/linuxsoftware/joyous

**Comment by Jean-Zombie** [comment]
… regarding "Transifex". Not sure either. Looks expensive ;-)

**Comment by linuxsoftware** [comment]
They support open source projects https://docs.transifex.com/projects/open-source-project

**Comment by linuxsoftware** [comment]
Thanks for your translation.  Great to get!  Please let me know if you can think of how the i18n can be improved.
