### ISSUE TITLE
getAllUpcomingEvents

### ISSUE THREAD

**Issue by lucasrohlf** [linuxsoftware/ls.joyous#16]
Hi!
I was using getAllUpcomingEvents in a tag to create a list of upcoming events. I just updated to 0.9.0 and the only thing not working is pulling the upcoming event date information. I was using 'when' 'title' 'url' but when isn't working. Has this been changed/retitled? I'm new to this...

Thx

**Comment by lucasrohlf** [comment]
Got it. I edited
{% for title, event in events|slice:":4" %}
to
{% for title, event, url in events|slice:":4" %}

**Comment by linuxsoftware** [comment]
Great!  Glad you got it working.

Yes, I added a separate url field in 0.8.2
https://joyous.readthedocs.io/en/latest/releases/0.8.2.html#thisevent
