### ISSUE TITLE
Internationalize Joyous so the formats and strings can be localized

### ISSUE THREAD

**Issue by linuxsoftware** [linuxsoftware/ls.joyous#2]
Is I18n and L10n important to you?  Let me know if so, because currently Joyous is mostly hardcoded.

**Comment by acerix** [comment]
Thanks for this app :)

I was able to easily translate the content using https://github.com/infoportugal/wagtail-modeltranslation by adding this to my app's translation.py:

```
from ls.joyous.models import GroupPage, EventBase, EventCategory, SimpleEventPage, MultidayEventPage, RecurringEventPage, ExtraInfoPage, CalendarPage

@register(GroupPage)
class GroupPageTR(TranslationOptions):
    fields = (
        'content',
    )

@register(EventBase)
class EventBaseTR(TranslationOptions):
    fields = (
        'details',
        'location',
        'website',
    )

@register(EventCategory)
class EventCategoryTR(TranslationOptions):
    fields = (
        'name',
    )

@register(SimpleEventPage)
class SimpleEventPageTR(TranslationOptions):
    fields = (
    )

@register(MultidayEventPage)
class SimpleEventPageTR(TranslationOptions):
    fields = (
    )

@register(RecurringEventPage)
class RecurringEventPageTR(TranslationOptions):
    fields = (
    )

@register(CalendarPage)
class CalendarPageTR(TranslationOptions):
    fields = (
        'intro',
    )

@register(ExtraInfoPage)
class ExtraInfoPageTR(TranslationOptions):
    fields = (
        'extra_title',
        'extra_information',
    )

```

I think you can add something like that to the repo to add support for wagtail-modeltranslation, let me know if you'd like a PR.

**Comment by linuxsoftware** [comment]
Thanks!  I will give that a go.  I think there will still be some unlocalized strings, (e.g. the when property), but every improvement is very welcome.

**Comment by acerix** [comment]
Yes, the dates show up in the correct language but most text is hardcoded, for example:

https://github.com/linuxsoftware/ls.joyous/blob/master/ls/joyous/templates/joyous/calendar_list_upcoming.html#L17

I plan to make a branch soon that makes the text translatable by django like this:

https://docs.djangoproject.com/en/dev/topics/i18n/translation/#std:templatetag-trans

**Comment by linuxsoftware** [comment]
Thanks!  A PR when you are ready would be most welcome.

**Comment by acerix** [comment]
My fork now has support for wagtail-modeltranslation and has most basic text translated to French.  I didn't translate anything JavaScript yet.  

Would you consider a library like FullCalendar for the month and week views? It handles all the translations which would take long to implement otherwise. 

https://fullcalendar.io/releases/fullcalendar/3.9.0/demos/locales.html

**Comment by linuxsoftware** [comment]
Great.

Yes, using FullCalendar seems a good idea.  Ideally I'd like to continue to support the plain HTML calendars too.  Maybe using template overloading to switch between the two.

**Comment by acerix** [comment]
That makes sense, although I wasn't able to find any obvious way to overload templates within an app.

Is there a way to add a new setting (eg. `JOYOUS_USE_FULLCALENDAR`) that when enabled would look for templates in another directory first (eg. templates/joyous-fullcalendar/), then fall back to the main template dir for any templates not copied there?

If not, I figure that could be done with a new template back-end, or maybe by making a new app that extends Joyous, but would rather a simpler solution.

**Comment by linuxsoftware** [comment]
Hi @acerix  I'm back to looking at Joyous again. I've merged your i18n changes into a branch https://github.com/linuxsoftware/ls.joyous/tree/i18n on my repository, and am working at completing it there.  My French translation is from Google so will be awful.  Corrections would be very welcome.  Did you get any further on implementing a FullCalendar front end?  If you do I would be happy to consider a PR for it.   Thanks, David.

**Comment by acerix** [comment]
Thanks, looks good.  My French isn't the best but I looked through the translations you have and they seem fine.  I didn't get any further with FullCalendar, I couldn't figure out an elegant way to add it as an option and it wasn't really needed for my project but would be nice to have since it covers most of the missing i18n.

**Comment by linuxsoftware** [comment]
I am calling this issue done.  Thanks for your help acerix.  Hopefully this will let people use Joyous in their own languages.

**Comment by vbroskas** [comment]
@acerix I'm running into some issues trying to use [Modeltranslation](https://github.com/infoportugal/wagtail-modeltranslation) with the joyous calendar. When I add the translation options as you have above I get this error:
```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lo/Code/clients/nmafc/venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/home/lo/Code/clients/nmafc/venv/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/home/lo/Code/clients/nmafc/venv/lib/python3.6/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/lo/Code/clients/nmafc/venv/lib/python3.6/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/lo/Code/clients/nmafc/venv/lib/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/lo/Code/clients/nmafc/venv/lib/python3.6/site-packages/wagtail/admin/checks.py", line 63, in get_form_class_check
    if not issubclass(edit_handler.get_form_class(), WagtailAdminPageForm):
  File "/home/lo/Code/clients/nmafc/venv/lib/python3.6/site-packages/wagtail/admin/edit_handlers.py", line 369, in get_form_class
    widgets=self.widget_overrides())
  File "/home/lo/Code/clients/nmafc/venv/lib/python3.6/site-packages/wagtail/admin/edit_handlers.py", line 64, in get_form_for_model
    return metaclass(class_name, (form_class,), form_class_attrs)
  File "/home/lo/Code/clients/nmafc/venv/lib/python3.6/site-packages/wagtail/admin/forms/models.py", line 66, in __new__
    new_class = super(WagtailAdminModelFormMetaclass, cls).__new__(cls, name, bases, attrs)
  File "/home/lo/Code/clients/nmafc/venv/lib/python3.6/site-packages/modelcluster/forms.py", line 245, in __new__
    new_class = super(ClusterFormMetaclass, cls).__new__(cls, name, bases, attrs)
  File "/home/lo/Code/clients/nmafc/venv/lib/python3.6/site-packages/django/forms/models.py", line 266, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (utc2local, upload) specified for CalendarPage
```
If I take the calendar page out of my translation.py file, i then run into an error where I can't publish a calendar page. I get a validation error saying that the title field can't be empty, even though I have it filled in.

Any ideas? Thanks for any help you can provide!

**Comment by linuxsoftware** [comment]
Thanks for the report of this problem.  I have created a new Issue #33 for this.
