### ISSUE TITLE
Suggestion:  Sync with google

### ISSUE THREAD

**Issue by the-moog** [linuxsoftware/ls.joyous#21]
There are a few project: [Python Google Calendar API](https://pypi.org/project/python-google-calendar-api/) or [django-google-calendar](https://bitbucket.org/kingmray/django-google-calendar/src/master/) allows Python to read and write to a given Google calendar.

How about adding hooks to your code so that when events are created, assuming the client_secret.json file is present, then new calendar events (pages) would also populate Google calendar. Also some sort of hook (perhaps a cron) to merge events from Google calendar into Joyous.

**Comment by linuxsoftware** [comment]
Thanks for the suggestion and links.

You can already subscribe to a Joyous calendar in GoogleCalendar.  To do this:
1. Log in to your GoogleCalendar
1. Click "Other calendars +" (Add other calendars)
1. Choose "From URL"
1. Enter the url of your Joyous calendar with "?format=ical" on the end, e.g. http://demo.linuxsoftware.nz/joyous/?format=ical
1. Change any other settings you like (e.g. the calendar name)
1. Exit settings by clicking "<-" up the top-left.

GoogleCalendar will now display your Joyous events and will sync with changes that are made.

You can also export from GoogleCalendar and import in to a Joyous calendar.  To do this:
1. Log in to your GoogleCalendar
1. Choose Settings | Import & export | Export
1. Unzip the file that is downloaded
1. Log in to your Joyous calendar
1. Pick a calendar page, or create a new one.
1. Select the Settings tab
1. Choose the calendar (not the address book) file that you unzipped
1. Select “Publish” and events will be imported as published pages.

Joyous will now display your GoogleCalendar events, but you will have to manually repeat the process to re-sync them

**Comment by linuxsoftware** [comment]
I have added this info to the [Read the docs](https://joyous.readthedocs.io/en/latest/topics/integration.html)
