### ISSUE TITLE
Make the Export functionality optional

### ISSUE THREAD

**Issue by JorneVL** [linuxsoftware/ls.joyous#23]
The export function to iCal is unwanted in my use case.
Is it possible to disable this per page or in total with a setting?
I haven't found anything

**Comment by linuxsoftware** [comment]
To do this [override](https://docs.djangoproject.com/en/2.2/howto/overriding-templates/) the ``cal_footer`` and ``event_footer`` blocks of the templates you want to change.

i.e. add the following files to your app's template directory
``joyous/calendar_base.html``
`{% block cal_footer %}{% endblock cal_footer %}`

``joyous/calendar_list_upcoming.html``
`{% block cal_footer %}{% endblock cal_footer %}`

``joyous/event_base.html``
`{% block event_footer %}{% endblock event_footer %}`
