### ISSUE TITLE
FIRST_DAY_OF_WEEK doesn't work for monthly views

### ISSUE THREAD

**Issue by JorneVL** [linuxsoftware/ls.joyous#24]
I have set my Django Setting FIRST_DAY_OF_WEEK =1.
The first day of my calendar monthly view is still Sunday.
Any ideas why this doesn't work?

**Comment by linuxsoftware** [comment]
Do you have [USE_L10N](https://docs.djangoproject.com/en/2.2/ref/settings/#use-l10n) set to True?  If so, Django will first try and use [format localization](https://docs.djangoproject.com/en/2.2/topics/i18n/formatting/) to determine the format for the first day of the week.  E.g. for en_GB it is Monday, for en_AU it is Sunday.  See your ``django/conf/locale`` directory to find these format files.  If you want, you can create your own [custom format](https://docs.djangoproject.com/en/2.2/topics/i18n/formatting/#creating-custom-format-files).

**Comment by JorneVL** [comment]
Thanks, it's solved by setting this to False.

**Comment by linuxsoftware** [comment]
Update: I've added the setting JOYOUS_FIRST_DAY_OF_WEEK which if set will override the Django format.
