### ISSUE TITLE
Ongoing events

### ISSUE THREAD

**Issue by lucasrohlf** [linuxsoftware/ls.joyous#26]
Hi! quick question. I have multi-day events that disappear from my events list calendar while they are ongoing. Example "Ice Fest" runs from 1/10 to 1/12 but on 1/11 is not listed on my events list view or my Upcoming Events snippet. The event does show up on my calendar view. 

Is there a way around this behavior that I can add to my code for list/upcoming views? maybe a future checkbox on the event that "Show until event past"?

This would also be nice for visitors to the site to see what time the event goes till even after it has started.

**Comment by linuxsoftware** [comment]
I am going to have to think about this.  A check box to change the behaviour of individual events seems like it'd be quite complicated.  (And we won't know the value of the checkbox until we have fetched the event.)  Perhaps a new list of not-yet-finished events is needed that would return all events (single-day or multi-day, one-off or recurring) that have not finished.  What would it be called?  started-and-upcoming?

Meanwhile here is a monkey-patch that changes MultidayEventPage and MultidayEventQuerySet to work the way you want.  Include this code somewhere like the models.py of one of your apps and it will change the behaviour of Joyous. 

```
from ls.joyous.models.events import MultidayEventPage, MultidayEventQuerySet
from ls.joyous.utils.telltime import getLocalDatetime, todayUtc
from datetime import timedelta
from django.utils import timezone

def upcomingAndCurrent(self):
    qs = super(MultidayEventQuerySet, self).upcoming()
    return qs.filter(date_to__gte = todayUtc() - timedelta(1))
MultidayEventQuerySet.upcoming = upcomingAndCurrent

def upcomingFromDt(self):
    fromDt = getLocalDatetime(self.date_from, self.time_from, self.tz)
    toDt = getLocalDatetime(self.date_to, self.time_to, self.tz)
    return fromDt if toDt >= timezone.localtime() else None
MultidayEventPage._upcoming_datetime_from = property(upcomingFromDt)
```

Hope it helps.  May contain bugs.  No guarantee for future compatibility.

**Comment by lucasrohlf** [comment]
Thank you!

**Comment by linuxsoftware** [comment]
I have added a new setting JOYOUS_UPCOMING_INCLUDES_STARTED. If this is set to True then the list of upcoming events will also include events that have already started but have not yet finished.
This will be in the next release of Joyous (0.9.5).
