### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by yukilab2** [linuxsoftware/ls.joyous#30]
- [ ] Japanese i18n resource
- [ ] presentation format (such as  year - month - day  presentation order)

**Comment by yukilab2** [comment]
working on my fork now.

**Comment by linuxsoftware** [comment]
Great, thanks.  Please let me know if I can help with any code changes.

**Comment by linuxsoftware** [comment]
Your translation looks complete so I am going to go ahead and merge it in.  Hope this is ok?
