### ISSUE TITLE
Extending ls.joyous for writing pages

### ISSUE THREAD

**Issue by AdrienLemaire** [linuxsoftware/ls.joyous#7]
Hi, and thanks for making ls.joyous.

I need to extend Wagtail with "tasks" to manage the writing of blog posts (add deadlines to writing, reviewing and publishing, and reschedule on a monthly basis).
I'm wondering if I could extend ls.joyous "events" for that purpose.

I'm expecting a negative reply, but I'd appreciated it if you have recommendations on more suited apps to extend from.
Otherwise, I'll start building a new wagtail-tasks application from scratch for that purpose, following the wagtail-review logic.

**Comment by linuxsoftware** [comment]
Hi @Fandekasp,

Adding tasks to Joyous is a new and interesting idea for me.  Tasks and events *do* often go together in Groupware applications, and the iCalendar format (RFC 5545) specifies VTODO alongside VEVENT.  But tasks are quite different to events and I don't see there could be much code reuse.  You could extend the ls.joyous.models.Calendar to display tasks by their due date, but that's probably only worth doing if you want to mix events and tasks on the same calendar.

Have you looked at https://github.com/shacker/django-todo?  Maybe that would be a useful starting point.

Or, if you start from scratch I have a few suggestions:
* Recurring events, iCal and time zones are where most of my complexity comes from.  Do you need to support these?  If so design for them up front.
* pytz and https://github.com/mfogel/django-timezone-field for  timezones
* https://github.com/spulec/freezegun is fantastic for date dependant tests
* https://github.com/collective/icalendar for iCal export/import
* and dateutil.rrule for recurring dates

Hope that helps.  Best wishes for your project!
David.

**Comment by AdrienLemaire** [comment]
David, thank you for your warm reply, you just made my day :)

I didn't know about django-todo, and it looks very nice. I'll spend some time investigating how we could integrate it to wagtail.

Best regards
